name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - id: 'compile'
      uses: rhysnewell/rust-cargo-musl-action@master
      with:
        command: 'build'
    # - name: Run tests
    #   run: cargo test --verbose
    - name: Server Bin
      uses: actions/upload-artifact@v4
      with:
        name: server
        path: ${{ steps.compile.outputs.release-dir }}/server
    - name: Client Bin
      uses: actions/upload-artifact@v4
      with:
        name: client
        path: ${{ steps.compile.outputs.release-dir }}/client
